### ISSUE TITLE
pre标签显示

### ISSUE THREAD

**Issue by moshanghan** [dwqs/mpvue-markdown-parser#1]
不支持pre标签吗
pre标签内部的代码直接就没了
![image](https://user-images.githubusercontent.com/30591457/42279900-cc905e18-7fd1-11e8-8109-b8bf08d0fa7b.png)
可以解析markdonw 可以解析code，不能解析pre 标签？

**Comment by dwqs** [comment]
![ss](https://user-images.githubusercontent.com/7871813/41891003-db5ed8f4-7944-11e8-8409-2a5bedd736e1.png)

小程序不支持 pre 标签，对代码的渲染是直接用 `code` 标签了：https://github.com/dwqs/mpvue-markdown-parser/blob/master/src/index.js#L16

如果你用 mpvue-markdown-parser 不能正常解析 code ，能贴下你的 markdown 文本？

**Comment by moshanghan** [comment]
不是markdown 是pre标签包裹的代码 ，来自wordpress的高亮代码
markdown显示没有问题

**Comment by dwqs** [comment]
目前只支持  markdown 的

**Comment by moshanghan** [comment]
我看你打的广告才用的这个，到头来只支持markdown，太失望了
........... @dwqs
